/* UI chrome only (EN/हिं). Source reports are always shown unchanged. */

export type Lang = "en" | "hi";

const STRINGS = {
  appTitle: { en: "Safety Report Triage", hi: "सुरक्षा रिपोर्ट ट्रायाज" },
  appTitleShort: { en: "Safety Triage", hi: "सुरक्षा ट्रायाज" },
  appSub: { en: "OIL India", hi: "OIL इंडिया" },
  tabTriage: { en: "Triage", hi: "ट्रायाज" },
  tabInsights: { en: "Insights", hi: "इनसाइट्स" },
  tabDecisions: { en: "Decisions", hi: "निर्णय" },
  tabHistory: { en: "Decision history", hi: "निर्णय इतिहास" },
  workspaceTriage: { en: "Review the reports that need attention", hi: "ध्यान देने योग्य रिपोर्टों की समीक्षा करें" },
  workspaceTriageSub: {
    en: "Priorities, evidence and human decisions in one queue.",
    hi: "प्राथमिकता, साक्ष्य और मानवीय निर्णय — एक ही कतार में।",
  },
  workspaceInsights: { en: "Where should the HSE team focus next?", hi: "HSE टीम को आगे कहाँ ध्यान देना चाहिए?" },
  workspaceDecisions: { en: "Decision history", hi: "निर्णय इतिहास" },
  confirm: { en: "Confirm SIF-potential", hi: "SIF-क्षमता की पुष्टि करें" },
  notSif: { en: "Not SIF-potential", hi: "SIF-क्षमता नहीं" },
  flaggedFor: { en: "Flagged for HSE review", hi: "HSE समीक्षा के लिए चिह्नित" },
  noAction: { en: "Low review priority", hi: "कम समीक्षा प्राथमिकता" },
  highPriority: { en: "High review priority", hi: "उच्च समीक्षा प्राथमिकता" },
  moderatePriority: { en: "Moderate review priority", hi: "मध्यम समीक्षा प्राथमिकता" },
  ruleProbs: { en: "Matching life-saving rules", hi: "मेल खाते जीवन-रक्षक नियम" },
  footer: {
    en: "Model proposes, HSE disposes. Your decision becomes a training label.",
    hi: "मॉडल प्रस्तावित करता है — HSE निपटान करता है। आपका निर्णय प्रशिक्षण लेबल बनता है।",
  },
  triageScore: { en: "triage score", hi: "ट्रायाज स्कोर" },
  rerank: { en: "Run demo batch", hi: "डेमो बैच चलाएँ" },
  importCsv: { en: "Import CSV", hi: "CSV आयात करें" },
  ingesting: { en: "Ingesting reports…", hi: "रिपोर्ट इनजेस्ट हो रही हैं…" },
  ingestedDone: { en: "Batch ingested — re-ranked", hi: "बैच इनजेस्ट — पुनः रैंक" },
  ingestConfirm: {
    en: "Ingest the 500-report demo batch? Real classification, about 15 seconds. This runs once per session.",
    hi: "500-रिपोर्ट डेमो बैच इनजेस्ट करें? वास्तविक वर्गीकरण, लगभग 15 सेकंड। प्रति सत्र एक बार।",
  },
  ingestFailed: {
    en: "Ingest failed — live data unchanged. Check the API and retry.",
    hi: "इनजेस्ट विफल — लाइव डेटा अपरिवर्तित। API जाँचें, पुनः प्रयास करें।",
  },
  awaiting: { en: "Needs review", hi: "समीक्षा आवश्यक" },
  overrides: { en: "Recorded decisions", hi: "दर्ज निर्णय" },
  reportQueue: { en: "Work queue", hi: "कार्य कतार" },
  whyScore: { en: "Why this score?", hi: "यह स्कोर क्यों?" },
  nearDupBanner: {
    en: "Matches a training record — memory, not generalization",
    hi: "प्रशिक्षण रिकॉर्ड से मेल — सामान्यीकरण नहीं, स्मृति",
  },
  chunkedBadge: { en: "Scored in sections — long report", hi: "खंडों में स्कोर — लंबी रिपोर्ट" },
  llmPhrased: { en: "phrased by local LLM", hi: "स्थानीय LLM द्वारा पुनर्लिखित" },
  pasteTitle: { en: "Classify a report", hi: "रिपोर्ट वर्गीकृत करें" },
  pastePlaceholder: {
    en: "Paste a UA/UC or near-miss report here…",
    hi: "UA/UC या नियर-मिस रिपोर्ट यहाँ पेस्ट करें…",
  },
  pasteButton: { en: "Classify", hi: "वर्गीकृत करें" },
  pasteBusy: { en: "Classifying…", hi: "वर्गीकरण जारी…" },
  pasteHint: { en: "Ctrl+Enter to classify", hi: "Ctrl+Enter से वर्गीकृत करें" },
  liveChip: { en: "LIVE", hi: "लाइव" },
  offlineNote: {
    en: "API unreachable — offline placeholder, not a score",
    hi: "API अनुपलब्ध — ऑफ़लाइन प्लेसहोल्डर, स्कोर नहीं",
  },
  statusOnline: { en: "Online", hi: "ऑनलाइन" },
  statusOffline: { en: "Offline demo", hi: "ऑफ़लाइन डेमो" },
  reportsIndexed: { en: "reports indexed", hi: "रिपोर्ट अनुक्रमित" },
  densitySub: {
    en: "Sites ranked by flagged near-miss density — where to inspect next",
    hi: "चिह्नित नियर-मिस घनत्व से क्रमित साइटें — अगला निरीक्षण कहाँ",
  },
  overridesNote: {
    en: "An audit trail of HSE review outcomes",
    hi: "HSE समीक्षा परिणामों का ऑडिट रिकॉर्ड",
  },
  colReport: { en: "Report", hi: "रिपोर्ट" },
  colField: { en: "Field", hi: "फ़ील्ड" },
  colWas: { en: "Was", hi: "पहले" },
  colNow: { en: "Now", hi: "अब" },
  colReviewer: { en: "Reviewer", hi: "समीक्षक" },
  colWhen: { en: "When", hi: "समय" },
  filterAll: { en: "All reports", hi: "सभी रिपोर्ट" },
  filterPriority: { en: "Priority queue", hi: "प्राथमिकता कतार" },
  filterReview: { en: "Needs decision", hi: "निर्णय आवश्यक" },
  filterReviewed: { en: "Reviewed", hi: "समीक्षित" },
  filterInformational: { en: "No review needed", hi: "समीक्षा आवश्यक नहीं" },
  filterDuplicate: { en: "Duplicates", hi: "डुप्लिकेट" },
  searchReports: { en: "Search reports", hi: "रिपोर्ट खोजें" },
  noMatchingReports: { en: "No reports match these filters.", hi: "इन फ़िल्टरों से कोई रिपोर्ट मेल नहीं खाती।" },
  manualReview: { en: "Manual review required", hi: "मानवीय समीक्षा आवश्यक" },
  technicalDetail: { en: "Technical detail", hi: "तकनीकी विवरण" },
  decisionSaved: { en: "Decision recorded", hi: "निर्णय दर्ज हुआ" },
  alreadyReviewed: { en: "Reviewed by HSE", hi: "HSE द्वारा समीक्षित" },
  recordOutcome: { en: "Record review outcome", hi: "समीक्षा परिणाम दर्ज करें" },
  optionalReview: {
    en: "Optional — record an outcome only when this report is formally reviewed.",
    hi: "वैकल्पिक — परिणाम तभी दर्ज करें जब रिपोर्ट की औपचारिक समीक्षा हो।",
  },
  priorityGuidance: {
    en: "Work from the top as capacity allows. These are recommendations, not mandatory confirmations.",
    hi: "उपलब्ध क्षमता के अनुसार ऊपर से काम करें। ये सुझाव हैं, अनिवार्य पुष्टि नहीं।",
  },
  locations: { en: "Locations", hi: "स्थान" },
  recurringPatterns: { en: "Recurring patterns", hi: "दोहराते पैटर्न" },
  siteActivity: { en: "Site × activity", hi: "साइट × गतिविधि" },
  activityBarrier: { en: "Activity × failed barrier", hi: "गतिविधि × विफल अवरोध" },
  demoDisclosure: { en: "Synthetic OIL-style demo data", hi: "कृत्रिम OIL-शैली डेमो डेटा" },
  queueHelp: {
    en: "Why some reports need manual review",
    hi: "कुछ रिपोर्टों को मानवीय समीक्षा क्यों चाहिए",
  },
  emptyQueue: {
    en: "No reports yet. Classify a report or import a CSV to begin.",
    hi: "अभी कोई रिपोर्ट नहीं। शुरू करने के लिए रिपोर्ट वर्गीकृत करें या CSV आयात करें।",
  },
  skipContent: { en: "Skip to content", hi: "मुख्य सामग्री पर जाएँ" },
  hseOperations: { en: "HSE operations", hi: "HSE संचालन" },
  operationalOverview: { en: "Operational overview", hi: "संचालन अवलोकन" },
  patternSiteBlurb: {
    en: "Recurring activity and site combinations that may warrant a planned inspection.",
    hi: "बार-बार दिखने वाले गतिविधि और साइट संयोजन जिनके लिए नियोजित निरीक्षण आवश्यक हो सकता है।",
  },
  patternBarrierBlurb: {
    en: "Repeated activity and failed-barrier combinations that show where safeguards break down.",
    hi: "दोहराते गतिविधि और विफल-अवरोध संयोजन जो बताते हैं कि सुरक्षा उपाय कहाँ टूट रहे हैं।",
  },
  noPatterns: { en: "No patterns yet. Import more reports to begin.", hi: "अभी कोई पैटर्न नहीं। शुरू करने के लिए और रिपोर्ट आयात करें।" },
  reportsReviewed: { en: "reports reviewed", hi: "रिपोर्ट समीक्षित" },
  flaggedPer100: { en: "flagged per 100", hi: "प्रति 100 चिह्नित" },
  statisticalDetail: { en: "Statistical detail", hi: "सांख्यिकीय विवरण" },
  showTop10: { en: "Show top 10 only", hi: "केवल शीर्ष 10 दिखाएँ" },
  showAllPatterns: { en: "Show all patterns", hi: "सभी पैटर्न दिखाएँ" },
  showTop20: { en: "Show top 20 only", hi: "केवल शीर्ष 20 दिखाएँ" },
  showAllLocations: { en: "Show all locations", hi: "सभी स्थान दिखाएँ" },
  noDecisions: { en: "No decisions recorded yet", hi: "अभी कोई निर्णय दर्ज नहीं" },
  noDecisionsBody: {
    en: "Review a report in Triage and record an outcome. It will appear here as part of the audit trail.",
    hi: "ट्रायाज में रिपोर्ट की समीक्षा कर परिणाम दर्ज करें। वह यहाँ ऑडिट रिकॉर्ड में दिखाई देगा।",
  },
  queueFilters: { en: "Queue filters", hi: "कतार फ़िल्टर" },
  pastedNow: { en: "Pasted just now in this session", hi: "इस सत्र में अभी पेस्ट किया गया" },
  possibleDuplicate: { en: "Possible duplicate", hi: "संभावित डुप्लिकेट" },
  gateShort: { en: "Review", hi: "समीक्षा" },
  wellControlTag: { en: "Well-control / barrier tag", hi: "वेल-कंट्रोल / अवरोध टैग" },
  loadingExplanation: { en: "Loading explanation", hi: "व्याख्या लोड हो रही है" },
  explanationUnavailable: {
    en: "Explanation is unavailable while the service is offline.",
    hi: "सेवा ऑफ़लाइन होने पर व्याख्या उपलब्ध नहीं है।",
  },
  cached: { en: "cached", hi: "संग्रहीत" },
  rank: { en: "Rank", hi: "रैंक" },
  site: { en: "Site", hi: "साइट" },
  reports: { en: "Reports", hi: "रिपोर्ट" },
  flagged: { en: "Flagged", hi: "चिह्नित" },
  flagRate: { en: "Flag rate", hi: "चिह्नित दर" },
  movement: { en: "Movement", hi: "बदलाव" },
  climbedToFirst: { en: "just climbed to #1", hi: "अभी #1 पर पहुँचा" },
} as const;

export type StringKey = keyof typeof STRINGS;

export function t(lang: Lang, key: StringKey): string {
  return STRINGS[key][lang];
}
